name: Build and publish docs
on:
  push:
    branches:
      - master
jobs:
  build-and-publish:
    concurrency: docs-${{ github.ref }} #to stop simultaneous docs builds
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ["1.7"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Julia ${{ matrix.julia-version }}
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - name: Install Documenter
        run: julia -e 'using Pkg; Pkg.add("Documenter")'
      - name: Install SNMRForward in Julia
        run: |
          julia -e 'using Pkg; Pkg.develop(path=".")'
      - name: Build docs
        run: |
          cd docs
          julia make.jl
      - name: Publish docs
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: docs/build
